steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-todo-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-todo-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'flask-todo-app', '--source=.', '--region=us-central1', '--platform=managed', '--allow-unauthenticated']
images: []